; PlatformIO Project Configuration File
; picoControl – WiFi vacuum robot (STOFZUIGER)
; Board: Raspberry Pi Pico W (earlephilhower Arduino core)

[env:picow]
platform     = https://github.com/maxgerhardt/platform-raspberrypi.git
board        = rpipicow
board_build.core = earlephilhower
framework    = arduino

lib_deps =
    adafruit/Adafruit SSD1306@^2.5.11
    adafruit/Adafruit GFX Library@^1.11.10
    robtillaart/PCA9635@^0.6.0
